// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using olegity.Data;

#nullable disable

namespace olegity.Migrations.AnimatedDBContentMigrations
{
    [DbContext(typeof(AnimatedDBContent))]
    [Migration("20240530141753_test11")]
    partial class test11
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("olegity.Data.Models.Animated", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AnimatedClipsID")
                        .HasColumnType("int");

                    b.Property<int>("animatedVideosID")
                        .HasColumnType("int");

                    b.Property<string>("link")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("AnimatedClipsID");

                    b.ToTable("Animated");
                });

            modelBuilder.Entity("olegity.Data.Models.AnimatedClips", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("img")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("pageID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.ToTable("AnimatedClips");
                });

            modelBuilder.Entity("olegity.Data.Models.Animated", b =>
                {
                    b.HasOne("olegity.Data.Models.AnimatedClips", "AnimatedClips")
                        .WithMany("AnimatedVideos")
                        .HasForeignKey("AnimatedClipsID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AnimatedClips");
                });

            modelBuilder.Entity("olegity.Data.Models.AnimatedClips", b =>
                {
                    b.Navigation("AnimatedVideos");
                });
#pragma warning restore 612, 618
        }
    }
}
